using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuizServer.Models;
using QuizServer.Repository;

namespace QuizServer.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class EventController : ControllerBase
    {
        private readonly EventRepository _eventRepo;

        public EventController(EventRepository eventRepo)
        {
            _eventRepo = eventRepo;
        }

        // GET: api/EventMaster
        [HttpGet]
        public async Task<ActionResult<IEnumerable<EventMaster>>> GetAll()
        {
            var list = await _eventRepo.getAllEventsAsync();
            return Ok(list);
        }

        // GET: api/EventMaster/{id}
        [HttpGet("{id:int}")]
        public async Task<ActionResult<EventMaster>> GetById(int id)
        {
            var subject = await _eventRepo.getEventByIdAsync(id);
            if (subject == null) return NotFound();
            return Ok(subject);
        }

        // GET: api/EventMaster/ByName/{name}
        [HttpGet("ByName/{name}")]
        public async Task<ActionResult<EventMaster>> GetByName(string name)
        {
            if (string.IsNullOrWhiteSpace(name)) return BadRequest("Event Name is required.");
            var subject = await _eventRepo.getEventByNameAsync(name);
            if (subject == null) return NotFound();
            return Ok(subject);
        }

        // POST: api/EventMaster
        [HttpPost]
        public async Task<ActionResult<EventMaster>> Create([FromBody] EventMaster subject)
        {
            subject.CreatedBy = "Admin";
            subject.CreatedOn = System.DateTime.Now;
            subject.IsDeleted = "N";
            subject.IsActive = "Y";
            if (subject == null) return BadRequest("Event data is invalid.");

            await _eventRepo.addEventAsync(subject);

            // assumes SubId is generated by the database
            return CreatedAtAction(nameof(GetById), new { id = subject.EventId }, subject);
        }

        // PUT: api/EventMaster/{id}
        [HttpPut("{id:int}")]
        public async Task<IActionResult> Update(int id, [FromBody] EventMaster subject)
        {
            if (subject == null) return BadRequest("Event data is required.");

            var existing = await _eventRepo.getEventByIdAsync(id);
            if (existing == null) return NotFound();

            // ensure identity matches route
            subject.EventId = id;
            await _eventRepo.updateEventAsync(subject);

            return NoContent();
        }

        // DELETE: api/EventMaster/{id}
        [HttpDelete("{id:int}")]
        public async Task<IActionResult> Delete(int id)
        {
            var existing = await _eventRepo.getEventByIdAsync(id);
            if (existing == null) return NotFound();

            await _eventRepo.removeEventAsync(id);
            return NoContent();
        }
    }
}
