using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuizServer.Models;
using QuizServer.Repository;

namespace QuizServer.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class InstructionController : ControllerBase
    {
        private readonly InstructionRepository _eventRepo;

        public InstructionController(InstructionRepository eventRepo)
        {
            _eventRepo = eventRepo;
        }
        // GET: api/Instruction
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Instruction>>> GetAll()
        {
            var list = await _eventRepo.getAllInstructionsAsync();
            return Ok(list);
        }
        // GET: api/Instruction/{id}
        [HttpGet("{id:int}")]
        public async Task<ActionResult<Instruction>> GetById(int id)
        {
            var subject = await _eventRepo.getInstructionByIdAsync(id);
            if (subject == null) return NotFound();
            return Ok(subject);
        }
        // GET: api/Instruction/ByName/{name}
        [HttpGet("ByName/{name}")]
        public async Task<ActionResult<Instruction>> GetByName(string name)
        {
            if (string.IsNullOrWhiteSpace(name)) return BadRequest("Instruction is required.");
            var subject = await _eventRepo.getInstructionByNameAsync(name);
            if (subject == null) return NotFound();
            return Ok(subject);
        }
        // POST: api/Instruction
        [HttpPost]
        public async Task<ActionResult<Instruction>> Create([FromBody] Instruction subject)
        {
            subject.CreatedBy = "Admin";
            subject.CreatedOn = System.DateTime.Now;
            subject.IsDeleted = "N";
            subject.IsActive = "Y";
            if (subject == null) return BadRequest("Event data is invalid.");

            await _eventRepo.addInstructionAsync(subject);

            // assumes SubId is generated by the database
            return CreatedAtAction(nameof(GetById), new { id = subject.EventId }, subject);
        }

        // PUT: api/Instruction/{id}
        [HttpPut("{id:int}")]
        public async Task<IActionResult> Update(int id, [FromBody] Instruction subject)
        {
            if (subject == null) return BadRequest("Instruction data is required.");

            var existing = await _eventRepo.getInstructionByIdAsync(id);
            if (existing == null) return NotFound();
            // ensure identity matches route
            subject.EventId = id;
            await _eventRepo.updateInstructionAsync(subject);
            return NoContent();
        }
        // DELETE: api/Instruction/{id}
        [HttpDelete("{id:int}")]
        public async Task<IActionResult> Delete(int id)
        {
            var existing = await _eventRepo.getInstructionByIdAsync(id);
            if (existing == null) return NotFound();
            await _eventRepo.removeInstructionAsync(id);
            return NoContent();
        }
    }
}
