using Microsoft.AspNetCore.Mvc;
using QuizServer.Repository;
using QuizServer.Models;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace QuizServer.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SubjectMasterController : ControllerBase
    {
        private readonly SubjectMasterRepository _subjectRepo;

        public SubjectMasterController(SubjectMasterRepository subjectRepo)
        {
            _subjectRepo = subjectRepo;
        }

        // GET: api/SubjectMaster
        [HttpGet]
        public async Task<ActionResult<IEnumerable<SubjectMaster>>> GetAll()
        {
            var list = await _subjectRepo.getAllSubjectsAsync();
            return Ok(list);
        }

        // GET: api/SubjectMaster/{id}
        [HttpGet("{id:int}")]
        public async Task<ActionResult<SubjectMaster>> GetById(int id)
        {
            var subject = await _subjectRepo.getSubjectByIdAsync(id);
            if (subject == null) return NotFound();
            return Ok(subject);
        }

        // GET: api/SubjectMaster/ByName/{name}
        [HttpGet("ByName/{name}")]
        public async Task<ActionResult<SubjectMaster>> GetByName(string name)
        {
            if (string.IsNullOrWhiteSpace(name)) return BadRequest("Name is required.");
            var subject = await _subjectRepo.getSubjectByNameAsync(name);
            if (subject == null) return NotFound();
            return Ok(subject);
        }

        // POST: api/SubjectMaster
        [HttpPost]
        public async Task<ActionResult<SubjectMaster>> Create([FromBody] SubjectMaster subject)
        {
            if (subject == null) return BadRequest("Subject data is invalid.");

            await _subjectRepo.addSubjectAsync(subject);

            // assumes SubId is generated by the database
            return CreatedAtAction(nameof(GetById), new { id = subject.SubId }, subject);
        }

        // PUT: api/SubjectMaster/{id}
        [HttpPut("{id:int}")]
        public async Task<IActionResult> Update(int id, [FromBody] SubjectMaster subject)
        {
            if (subject == null) return BadRequest("Subject data is required.");

            var existing = await _subjectRepo.getSubjectByIdAsync(id);
            if (existing == null) return NotFound();

            // ensure identity matches route
            subject.SubId = id;
            await _subjectRepo.updateSubjectAsync(subject);

            return NoContent();
        }

        // DELETE: api/SubjectMaster/{id}
        [HttpDelete("{id:int}")]
        public async Task<IActionResult> Delete(int id)
        {
            var existing = await _subjectRepo.getSubjectByIdAsync(id);
            if (existing == null) return NotFound();

            await _subjectRepo.removeSubjectAsync(id);
            return NoContent();
        }
    }
}