// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class CustomerMaster
{
    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateOnly? Dob { get; set; }

    public string Gender { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Email { get; set; }

    public string MobileNo { get; set; }

    public string Pwd { get; set; }

    public string CreatedBy { get; set; }

    public DateOnly? CreatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public DateOnly? UpdatedOn { get; set; }

    public string IsActive { get; set; }

    public string IsDeleted { get; set; }
}