// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class EventMaster
{
    public int EventId { get; set; }

    public string EventName { get; set; }

    public DateOnly? EventDate { get; set; }

    public string Description { get; set; }

    public string Medium { get; set; }

    public string Duration { get; set; }

    public string Status { get; set; }

    public string Remarks { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string IsActive { get; set; }

    public string IsDeleted { get; set; }

    public virtual ICollection<Instruction> Instructions { get; set; } = new List<Instruction>();
}