// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class EventSchedule
{
    public int ScheduleId { get; set; }

    public DateOnly? ScheduleDate { get; set; }

    public string Module { get; set; }

    public DateOnly? DeploymentDate { get; set; }

    public DateOnly? TestingDate { get; set; }

    public string TestingStatus { get; set; }

    public string Remarks { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }
}