// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class Instruction
{
    public int InstructionId { get; set; }

    public string Instruction1 { get; set; }

    public int? EventId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string IsActive { get; set; }

    public string IsDeleted { get; set; }

    public virtual EventMaster Event { get; set; }
}