// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class OrganizationMaster
{
    public int? OrganizationId { get; set; }

    public string RegNo { get; set; }

    public DateOnly? RegDate { get; set; }

    public string OrgName { get; set; }

    public string ContactPersonFname { get; set; }

    public string ContactPersonLname { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public decimal? ContactNo { get; set; }

    public decimal? AlterNetNo { get; set; }

    public string Email { get; set; }

    public string LogoPath { get; set; }

    public string CreatedBy { get; set; }

    public DateOnly? CreatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public DateOnly? UpdatedOn { get; set; }

    public string IsActive { get; set; }

    public string IsDeleted { get; set; }
}