// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace QuizServer.Models;

public partial class PerfectQuizAppDBContext : DbContext
{
    public PerfectQuizAppDBContext(DbContextOptions<PerfectQuizAppDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CustomerMaster> CustomerMasters { get; set; }

    public virtual DbSet<EventMaster> EventMasters { get; set; }

    public virtual DbSet<EventSchedule> EventSchedules { get; set; }

    public virtual DbSet<Instruction> Instructions { get; set; }

    public virtual DbSet<OrganizationMaster> OrganizationMasters { get; set; }

    public virtual DbSet<SubExpert> SubExperts { get; set; }

    public virtual DbSet<SubjectMaster> SubjectMasters { get; set; }

    public virtual DbSet<UserMaster> UserMasters { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("perfect_quiz");

        modelBuilder.Entity<CustomerMaster>(entity =>
        {
            entity.HasKey(e => e.FirstName).HasName("PK_UserRegistration");

            entity.ToTable("CustomerMaster");

            entity.Property(e => e.FirstName)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Address)
                .HasMaxLength(40)
                .IsUnicode(false);
            entity.Property(e => e.City)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.Dob).HasColumnName("DOB");
            entity.Property(e => e.Email)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Gender)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.IsActive)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.IsDeleted)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.LastName)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.MobileNo)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Pwd)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.State)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
        });

        modelBuilder.Entity<EventMaster>(entity =>
        {
            entity.HasKey(e => e.EventId);

            entity.ToTable("EventMaster");

            entity.Property(e => e.EventId).ValueGeneratedNever();
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(50);
            entity.Property(e => e.Duration).HasMaxLength(50);
            entity.Property(e => e.EventName).HasMaxLength(50);
            entity.Property(e => e.IsActive).HasMaxLength(10);
            entity.Property(e => e.IsDeleted).HasMaxLength(10);
            entity.Property(e => e.Medium).HasMaxLength(50);
            entity.Property(e => e.Remarks).HasMaxLength(50);
            entity.Property(e => e.Status).HasMaxLength(50);
        });

        modelBuilder.Entity<EventSchedule>(entity =>
        {
            entity.HasKey(e => e.ScheduleId);

            entity.ToTable("EventSchedule");

            entity.Property(e => e.ScheduleId).ValueGeneratedNever();
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Module).HasMaxLength(50);
            entity.Property(e => e.Remarks).HasMaxLength(50);
            entity.Property(e => e.TestingStatus).HasMaxLength(50);
        });

        modelBuilder.Entity<Instruction>(entity =>
        {
            entity.Property(e => e.InstructionId).ValueGeneratedNever();
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Instruction1).HasColumnName("Instruction");
            entity.Property(e => e.IsActive).HasMaxLength(10);
            entity.Property(e => e.IsDeleted).HasMaxLength(10);

            entity.HasOne(d => d.Event).WithMany(p => p.Instructions)
                .HasForeignKey(d => d.EventId)
                .HasConstraintName("FK_Instructions_EventMaster");
        });

        modelBuilder.Entity<OrganizationMaster>(entity =>
        {
            entity.HasKey(e => e.RegNo).HasName("PK_UserOrg");

            entity.ToTable("OrganizationMaster");

            entity.Property(e => e.RegNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Address)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.AlterNetNo).HasColumnType("numeric(18, 0)");
            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.ContactNo).HasColumnType("numeric(18, 0)");
            entity.Property(e => e.ContactPersonFname)
                .HasMaxLength(50)
                .HasColumnName("ContactPersonFName");
            entity.Property(e => e.ContactPersonLname)
                .HasMaxLength(50)
                .HasColumnName("ContactPersonLName");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.Email)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.IsActive)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.IsDeleted)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.LogoPath).HasMaxLength(50);
            entity.Property(e => e.OrgName)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.OrganizationId).HasColumnName("organizationId");
            entity.Property(e => e.Pwd)
                .HasMaxLength(50)
                .HasColumnName("pwd");
            entity.Property(e => e.State).HasMaxLength(50);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
        });

        modelBuilder.Entity<SubExpert>(entity =>
        {
            entity.HasKey(e => e.RegNo);

            entity.ToTable("SubExpert");

            entity.Property(e => e.RegNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Address)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.ContactNo)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.Email)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.IsActive)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.IsDeleted)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.LastName).HasMaxLength(20);
            entity.Property(e => e.ProfilePic).HasMaxLength(50);
            entity.Property(e => e.Pwd).HasMaxLength(50);
            entity.Property(e => e.SubExperties)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
        });

        modelBuilder.Entity<SubjectMaster>(entity =>
        {
            entity.HasKey(e => e.SubId);

            entity.ToTable("SubjectMaster");

            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.IsActive)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.IsDeleted)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.SubName)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy).HasMaxLength(50);
        });

        modelBuilder.Entity<UserMaster>(entity =>
        {
            entity.HasKey(e => e.UserName);

            entity.ToTable("UserMaster");

            entity.Property(e => e.UserName).HasMaxLength(50);
            entity.Property(e => e.Deg).HasMaxLength(50);
            entity.Property(e => e.IsActive)
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.IsDeleted)
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.LogIn).HasColumnType("datetime");
            entity.Property(e => e.LogOut).HasColumnType("datetime");
            entity.Property(e => e.Password).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}