// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class SubExpert
{
    public string RegNo { get; set; }

    public DateOnly? RegDate { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Address { get; set; }

    public string ContactNo { get; set; }

    public string Email { get; set; }

    public string SubExperties { get; set; }

    public byte[] ProfilePic { get; set; }

    public string Pwd { get; set; }

    public string CreatedBy { get; set; }

    public DateOnly? CreatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public DateOnly? UpdatedOn { get; set; }

    public string IsActive { get; set; }

    public string IsDeleted { get; set; }
}