// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class SubjectMaster
{
    public int SubId { get; set; }

    public string SubName { get; set; }

    public string CreatedBy { get; set; } = null;

    public DateOnly? CreatedOn { get; set; } = null;

    public string UpdatedBy { get; set; } = null;

    public DateOnly? UpdatedOn { get; set; } = null;

    public string IsActive { get; set; } = null;

    public string IsDeleted { get; set; } = null;
}