// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuizServer.Models;

public partial class UserMaster
{
    public string UserName { get; set; }

    public string Password { get; set; }

    public string Deg { get; set; }

    public DateTime? LogIn { get; set; }

    public DateTime? LogOut { get; set; }

    public string IsActive { get; set; }

    public string IsDeleted { get; set; }
}